all:
	make -C PicturePerfectEngine all install
	make -C TreeSerializerEngine all install
	make -C Garnet all install

.PHONY: clean
clean:
	make -C PicturePerfectEngine clean
	make -C TreeSerializerEngine clean
	make -C Garnet clean

distclean:
	make -C PicturePerfectEngine distclean
	make -C TreeSerializerEngine distclean
	make -C Garnet distclean

